roboptim::Polynomial< T > Class Template Reference
roboptim::Polynomial< T > Class Template Reference
Mathematical functions
Polynomial function.
#include <roboptim/core/function/polynomial.hh>
Public Member Functions
ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericTwiceDifferentiableFunction< T >)
Polynomial (vector_t coefficients)
Build a polynomial function.
virtual ~Polynomial ()
virtual std::ostream & print (std::ostream &o) const
Display the function on the specified output stream.
Protected Member Functions
void impl_compute (result_t &result, const argument_t &x) const
Function evaluation.
void impl_gradient (gradient_t &gradient, const argument_t &x, size_type) const
Gradient evaluation.
void impl_jacobian (jacobian_t &jacobian, const argument_t &x) const
Jacobian evaluation.
void impl_hessian (hessian_t &hessian, const argument_t &x, size_type) const
Hessian evaluation.
double applyPolynomial (const vector_t &coeffs, const argument_t &x) const
Implement Horner's method.
Detailed Description
template<typename T>
class roboptim::Polynomial< T >
Polynomial function.
Implement a polynomial function using the formula:
where polynomial coefficients are set when the class is instanciated
Examples:
finite-difference-gradient.cc, and function-polynomial.cc.
Constructor & Destructor Documentation
template<typename T> roboptim::Polynomial< T >::Polynomial (vector_t coefficients) [inline, explicit]
Build a polynomial function.
Parameters:
coefficients polynomial coefficients given in increasing degree order
Exceptions:
std::runtime_error
template<typename T> virtual roboptim::Polynomial< T >::~Polynomial () [inline, virtual]
Member Function Documentation
template<typename T> void roboptim::Polynomial< T >::impl_compute (result_t & result, const argument_t & argument) const [inline, protected, virtual]
Function evaluation.
Evaluate the function, has to be implemented in concrete classes.
Warning:
Do not call this function directly, call operator()(result_t&, const argument_t&) const instead.
Parameters:
result result will be stored in this vector
argument point at which the function will be evaluated
Implements roboptim::GenericFunction< T >.
References roboptim::Polynomial< T >::applyPolynomial().
template<typename T> virtual std::ostream& roboptim::Polynomial< T >::print (std::ostream & o) const [inline, virtual]
Display the function on the specified output stream.
Parameters:
o output stream used for display
Returns:
output stream
Reimplemented from roboptim::GenericTwiceDifferentiableFunction< T >.
References roboptim::decindent(), roboptim::iendl(), and roboptim::incindent().
template<typename T> roboptim::Polynomial< T >::ROBOPTIM_TWICE_DIFFERENTIABLE_FUNCTION_FWD_TYPEDEFS_ (GenericTwiceDifferentiableFunction< T >)