roboptim::CachedFunction< T > Class Template Reference
roboptim::CachedFunction< T > Class Template Reference
Function filters
Store previous function computation.
#include <roboptim/core/filter/cached-function.hh>
Public Types
typedef T::traits_t traits_t
Import traits type.
typedef
GenericDifferentiableFunction
< traits_t >::value_type value_type
Import value type.
typedef
GenericDifferentiableFunction
< traits_t >::size_type size_type
Import size type.
typedef
GenericDifferentiableFunction
< traits_t >::vector_t vector_t
Import vector type.
typedef
GenericDifferentiableFunction
< traits_t >::result_t result_t
Import result type.
typedef
GenericDifferentiableFunction
< traits_t >::argument_t argument_t
Import argument type.
typedef
GenericDifferentiableFunction
< traits_t >::gradient_t gradient_t
Import gradient type.
typedef
GenericTwiceDifferentiableFunction
< traits_t >::hessian_t hessian_t
Import hessian type.
typedef
GenericDifferentiableFunction
< traits_t >::jacobian_t jacobian_t
Import jacobian type.
typedef
GenericDifferentiableFunction
< traits_t >::interval_t interval_t
Import interval type.
typedef argument_t cacheKey_t
Key type for the cache.
typedef LRUCache< cacheKey_t,
vector_t > functionCache_t
typedef LRUCache< cacheKey_t,
gradient_t > gradientCache_t
typedef LRUCache< cacheKey_t,
jacobian_t > jacobianCache_t
typedef LRUCache< cacheKey_t,
hessian_t > hessianCache_t
Public Member Functions
CachedFunction (boost::shared_ptr< const T > fct, size_t size=10)
Cache a RobOptim function.
~CachedFunction ()
void reset ()
Reset the caches.
Protected Member Functions
virtual void impl_compute (result_t &result, const argument_t &argument) const
virtual void impl_gradient (gradient_t &gradient, const argument_t &argument, size_type functionId=0) const
virtual void impl_jacobian (jacobian_t &jacobian, const argument_t &arg) const
virtual void impl_hessian (hessian_t &hessian, const argument_t &argument, size_type functionId=0) const
virtual void impl_derivative (gradient_t &derivative, value_type argument, size_type order=1) const
template<>
void impl_gradient (gradient_t &, const argument_t &, size_type) const
template<>
void impl_gradient (gradient_t &, const argument_t &, size_type) const
template<>
void impl_jacobian (jacobian_t &, const argument_t &) const
template<>
void impl_jacobian (jacobian_t &, const argument_t &) const
template<>
void impl_hessian (hessian_t &, const argument_t &, size_type) const
template<>
void impl_hessian (hessian_t &, const argument_t &, size_type) const
template<>
void impl_hessian (hessian_t &, const argument_t &, size_type) const
template<>
void impl_hessian (hessian_t &, const argument_t &, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
template<>
void impl_derivative (gradient_t &, value_type, size_type) const
Protected Attributes
boost::shared_ptr< const T > function_
std::vector< functionCache_t > cache_
std::vector< gradientCache_t > gradientCache_
jacobianCache_t jacobianCache_
std::vector< hessianCache_t > hessianCache_
Detailed Description
template<typename T>
class roboptim::CachedFunction< T >
Store previous function computation.
When an expensive function is called several times at the same point (exactly!), the cached function prevents useless computation by caching the function result.
This filter is experimental in this release.
Member Typedef Documentation
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: argument_t roboptim::CachedFunction< T >::argument_t
Import argument type.
template<typename T> typedef argument_t roboptim::CachedFunction< T >::cacheKey_t
Key type for the cache.
template<typename T> typedef LRUCache<cacheKey_t, vector_t> roboptim::CachedFunction< T >::functionCache_t
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: gradient_t roboptim::CachedFunction< T >::gradient_t
Import gradient type.
template<typename T> typedef LRUCache<cacheKey_t, gradient_t> roboptim::CachedFunction< T >::gradientCache_t
template<typename T> typedef GenericTwiceDifferentiableFunction<traits_t>:: hessian_t roboptim::CachedFunction< T >::hessian_t
Import hessian type.
template<typename T> typedef LRUCache<cacheKey_t, hessian_t> roboptim::CachedFunction< T >::hessianCache_t
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: interval_t roboptim::CachedFunction< T >::interval_t
Import interval type.
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: jacobian_t roboptim::CachedFunction< T >::jacobian_t
Import jacobian type.
template<typename T> typedef LRUCache<cacheKey_t, jacobian_t> roboptim::CachedFunction< T >::jacobianCache_t
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: result_t roboptim::CachedFunction< T >::result_t
Import result type.
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: size_type roboptim::CachedFunction< T >::size_type
Import size type.
template<typename T> typedef T::traits_t roboptim::CachedFunction< T >::traits_t
Import traits type.
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: value_type roboptim::CachedFunction< T >::value_type
Import value type.
template<typename T> typedef GenericDifferentiableFunction<traits_t>:: vector_t roboptim::CachedFunction< T >::vector_t
Import vector type.
Constructor & Destructor Documentation
template<typename T > roboptim::CachedFunction< T >::CachedFunction (boost::shared_ptr< const T > fct, size_t size = 10) [explicit]
Cache a RobOptim function.
Parameters:
fct function to cache.
size size of the LRU cache.
template<typename T > roboptim::CachedFunction< T >::~CachedFunction ()
Member Function Documentation
template<typename T > void roboptim::CachedFunction< T >::impl_compute (result_t & result, const argument_t & argument) const [protected, virtual]
References roboptim::LRUCache< K, V >::find().
template<typename T > void roboptim::CachedFunction< T >::impl_derivative (gradient_t & derivative, value_type argument, size_type order = 1) const [protected, virtual]
References roboptim::derivative(), and roboptim::LRUCache< K, V >::find().
template<> void roboptim::CachedFunction< Function >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< SparseFunction >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< DifferentiableFunction >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< DifferentiableSparseFunction >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< TwiceDifferentiableFunction >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< TwiceDifferentiableSparseFunction >::impl_derivative (gradient_t & , value_type , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< Function >::impl_gradient (gradient_t & , const argument_t & , size_type) const [inline, protected]
template<typename T > void roboptim::CachedFunction< T >::impl_gradient (gradient_t & gradient, const argument_t & argument, size_type functionId = 0) const [protected, virtual]
template<> void roboptim::CachedFunction< SparseFunction >::impl_gradient (gradient_t & , const argument_t & , size_type) const [inline, protected]
template<typename T > void roboptim::CachedFunction< T >::impl_hessian (hessian_t & hessian, const argument_t & argument, size_type functionId = 0) const [protected, virtual]
template<> void roboptim::CachedFunction< Function >::impl_hessian (hessian_t & , const argument_t & , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< SparseFunction >::impl_hessian (hessian_t & , const argument_t & , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< DifferentiableFunction >::impl_hessian (hessian_t & , const argument_t & , size_type) const [inline, protected]
template<> void roboptim::CachedFunction< DifferentiableSparseFunction >::impl_hessian (hessian_t & , const argument_t & , size_type) const [inline, protected]
template<typename T > void roboptim::CachedFunction< T >::impl_jacobian (jacobian_t & jacobian, const argument_t & arg) const [protected, virtual]
References roboptim::LRUCache< K, V >::find().
template<> void roboptim::CachedFunction< Function >::impl_jacobian (jacobian_t & , const argument_t &) const [inline, protected]
template<> void roboptim::CachedFunction< SparseFunction >::impl_jacobian (jacobian_t & , const argument_t &) const [inline, protected]
template<typename T > void roboptim::CachedFunction< T >::reset ()
Reset the caches.
Member Data Documentation
template<typename T> std::vector<functionCache_t> roboptim::CachedFunction< T >::cache_ [mutable, protected]
template<typename T> boost::shared_ptr<const T> roboptim::CachedFunction< T >::function_ [protected]
template<typename T> std::vector<gradientCache_t> roboptim::CachedFunction< T >::gradientCache_ [mutable, protected]
template<typename T> std::vector<hessianCache_t> roboptim::CachedFunction< T >::hessianCache_ [mutable, protected]
template<typename T> jacobianCache_t roboptim::CachedFunction< T >::jacobianCache_ [mutable, protected]